name: Prettier

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run:
    name: 🕵️‍♀️
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: lts/*
      - run: npm install --ignore-scripts --only-dev
      - name: check if workflows needs prettier
        run: npx prettier --cache --check ".github/workflows/**/*.yml" || (echo "An action can't make changes to actions, you'll have to run prettier manually" && exit 1)
      - run: npx prettier --ignore-path .gitignore pnpm-lock.yaml --cache --write .
      - uses: EndBug/add-and-commit@v9.1.3
        with:
          default_author: github_actions
          commit: --no-verify
          message: '✨ Prettier formatted ✨'
